<?php
/*
 *  SOZO Design Ltd
 *
 *  NOTICE OF LICENSE
 *
 *  This source file is subject to the SOZO Proprietary EULA
 *  that is bundled with this package in the file LICENSE.
 *  It is also available through the world-wide-web at this URL:
 *  http://opensource.org/licenses/osl-3.0.php
 *
 *  @category    SOZO Design Ltd
 *  @package     Sozo_ZendeskChat
 *  @copyright   Copyright (c) SOZO Design Ltd (https://sozodesign.co.uk)
 *  @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php if ($widgetId = $block->getWidgetId()): ?>
    <!--Start of Zendesk Chat Script-->
    <script type="text/javascript">
        window.$zopim||(function(d,s){
            var z=$zopim=function(c){
                z._.push(c)
            },
            $=z.s= d.createElement(s),
            e=d.getElementsByTagName(s)[0];
            z.set=function(o){
                z.set._.push(o)
            };
            z._=[];z.set._=[];
            $.async=!0;
            $.setAttribute("charset","utf-8");
            $.src="https://v2.zopim.com/<?= $block->escapeHtml($widgetId)?>";
            z.t=+new Date;$.type="text/javascript";
            e.parentNode.insertBefore($,e)
        })(document,"script");
    </script>
    <!--End of Zendesk Chat Script-->
<?php endif;?>
