<?php
/*
 *  SOZO Design Ltd
 *
 *  NOTICE OF LICENSE
 *
 *  This source file is subject to the SOZO Proprietary EULA
 *  that is bundled with this package in the file LICENSE.
 *  It is also available through the world-wide-web at this URL:
 *  http://opensource.org/licenses/osl-3.0.php
 *
 *  @category    SOZO Design Ltd
 *  @package     Sozo_ZendeskChat
 *  @copyright   Copyright (c) SOZO Design Ltd (https://sozodesign.co.uk)
 *  @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style>
    #sozo-container {
        background: url('https://sozodesign.co.uk/images/magento/sozo_magento_plugin_about.png') no-repeat scroll 15px #e7efef;
        border: 1px solid #ccc;
        margin: 5px 0;
        padding: 15px 15px 15px 180px;
        min-height: 97px;
    }
</style>
<div id="sozo-container">
    <p>
        <strong>
            <?= $block->escapeHtml(__(sprintf('SOZO Design Zendesk Chat Plugin v%s.', $block->getVersion())));?>
        </strong> <br>
        <?= $block->escapeHtml(__('Magento 2 Zendesk Chat'));?><br>
    </p>
</div>

